export const rangeOfProducts = {
    "categories": {
        "ControlPanels": {
            "Products":
                {
                    "K923": {
                        "ItemCharacteristics":{
                            "ScreenResolution": "800x600",
                            "RAM": "1Gb",
                            "ModBusChannel": "1",
                            "PowerVoltage": "12V",
                        },
                        "Price": "190",
                        "image": "/img/Products/controlpanels/001.jpg",
                    },
                    "K927": {
                        "ItemCharacteristics": {
                            "ScreenResolution": "1024x768",
                            "RAM": "1Gb",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "550",
                        "image": "/img/Products/controlpanels/002.jpg",
                    },
                    "K1021": {
                        "ItemCharacteristics": {
                            "ScreenResolution": "1280x720",
                            "RAM": "1Gb",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "790",
                        "image": "/img/Products/controlpanels/003.jpg",
                    },
                },
        },
        "Controllers": {
            "Products":
                {
                    "MK120.01": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "16",
                            "NumberOfDigitalOutput": "32",
                            "ModBusChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "150",
                        "image": "/img/Products/controllers/001.jpg",
                    },
                    "MK120.03": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "16",
                            "NumberOfAnalogInput": "2",
                            "NumberOfAnalogOutput": "8",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "390",
                        "image": "/img/Products/controllers/002.jpg",
                    },
                    "MK120.05": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "8",
                            "NumberOfAnalogInput": "1",
                            "NumberOfAnalogOutput": "4",
                            "ModBusChannel": "2",
                            "PowerVoltage": "12V",
                        },
                        "Price": "420",
                        "image": "/img/Products/controllers/003.jpg",
                    },
                    "DVP20EX200T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "4",
                            "ModBusChannel": "1",
                            "RS-232": "1",
                            "TCPChannel": "1",
                            "CANopen": "master",
                            "Profibus":"slave",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "790",
                        "image": "/img/Products/controllers/004.jpg",
                    },
                    "DVP12SE11T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "4",
                            "NumberOfAnalogInput": "2",
                            "NumberOfAnalogOutput": "2",
                            "RS-232": "1",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "24V",
                        },
                        "Price": "590",
                        "image": "/img/Products/controllers/005.jpg",
                    },
                    "DVP28SV11T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "16",
                            "NumberOfDigitalOutput": "12",
                            "NumberOfAnalogInput": "4",
                            "NumberOfAnalogOutput": "2",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "590",
                        "image": "/img/Products/controllers/006.jpg",
                    },
                    "DVP14SS211T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/007.jpg",
                    },
                    "DVP14SS212TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/008.jpg",
                    },
                    "DVP14SS213TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/009.jpg",
                    },
                    "DVP14SS214TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/010.jpg",
                    },
                    "DVP14SS215TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/011.jpg",
                    },
                    "DVP14SS216TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/012.jpg",
                    },
                },
        },
        "Compact modules": {
            "Products":
                {
                    "MT-121": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "8",
                            "NumberOfAnalogInput": "3",
                            "NumberOfAnalogOutput": "1",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "750",
                        "image": "/img/Products/compactmodules/001.jpg",
                    },
                    "MT-151": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "Display": "OLED graphic display (128×64)",
                            "NumberOfDigitalInput": "16",
                            "NumberOfDigitalOutput": "12",
                            "NumberOfAnalogInputs": "6",
                            "NumberOfAnalogOutput": "1",
                            "RS-232": "1",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "USB": "Configurable USB-C port",
                            "Data and Event logger": "SD card",
                            "PowerVoltage": "12/24V",
                            "Battery Backup": "Buffered power supply (SLA battery support)",
                        },
                        "Price": "880",
                        "image": "/img/Products/compactmodules/002.jpg",
                    },
                    "MT-156": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "Display": "OLED graphic display (128×64)",
                            "NumberOfDigitalInput": "10",
                            "NumberOfDigitalOutput": "12",
                            "NumberOfAnalogInput": "2",
                            "RS-232": "1",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "USB": "Configurable USB-C port",
                            "Data and Event logger": "SD card",
                            "PowerVoltage": "12/24V",
                            "Battery Backup": "Buffered power supply (SLA battery support)",
                        },
                        "Price": "630",
                        "image": "/img/Products/compactmodules/003.jpg",
                    },
                },
        },
        "Special telemetry module": {
            "Products":
                {
                    "MT-651": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "GPS receiver":"Built-in with internal antenna and accelerometer",
                            "Measurement channels": "6",
                            "Temperature sensor": "Internal",
                            "Remote communication": "GPRS and SMS",
                            "ModBusChannel": "1",
                            "Battery power supply": "external power source as optional",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "377",
                        "image": "/img/Products/specialtelemetrymodule/001.jpg",
                    },
                    "MT-652": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "GPS receiver":"Built-in with internal antenna and accelerometer",
                            "Measurement channel": "6",
                            "Temperature sensor": "Internal",
                            "Remote communication": "GPRS and SMS",
                            "ModBusChannel": "1",
                            "Data logger":"capacity 180 000 records",
                            "Battery power supply": "external power source as optional",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "530",
                        "image": "/img/Products/specialtelemetrymodule/002.jpg",
                    },
                    "MT-513": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "2",
                            "AudioOutput": "1",
                            "Alarm transmission": "1",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "475",
                        "image": "/img/Products/specialtelemetrymodule/003.jpg",
                    },
                    "MT-221": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "Real Time Clock":"RTC",
                            "Data logger":"0.1 sec",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "320",
                        "image": "/img/Products/specialtelemetrymodule/004.jpg",
                    },
                    "MTX-2050": {
                        "ItemCharacteristics": {
                            "GSM module": "4G LTE Cat. 1 modem with 2G/3G Fallback",
                            "NumberOfDigitalInput": "4",
                            "SerialPort": "2",
                            "TCPChannel": "1",
                            "Real Time Clock":"RTC",
                            "Data logger":"0.1 sec",
                            "Processor for data rules transmission":"Built-in",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "320",
                        "image": "/img/Products/specialtelemetrymodule/005.jpg",
                    },
                },
        },
        "PowerSupplies": {
            "Products":
                {
                    "DR-15-15": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 220V",
                            "OutputVoltage": "DC 15V",
                            "Power": "15W",
                        },
                        "Price": "19",
                        "image": "/img/Products/powersupplies/001.jpg",
                    },
                    "DR-12-5": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 100~240V",
                            "OutputVoltage": "DC 5V",
                            "Power": "12W",
                            "Case" : "Plastic, DIN",
                        },
                        "Price": "15",
                        "image": "/img/Products/powersupplies/002.jpg",
                    },
                    "DR-60-15": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 100~240V",
                            "OutputVoltage": "DC 15V",
                            "Power": "60W",
                            "Case" : "Plastic, DIN",
                        },
                        "Price": "25",
                        "image": "/img/Products/powersupplies/003.jpg",
                    },
                    "DR-75-12": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 100~240V",
                            "OutputVoltage": "DC 12V",
                            "Power": "75W",
                            "Case" : "Plastic, DIN",
                        },
                        "Price": "27",
                        "image": "/img/Products/powersupplies/004.jpg",
                    },
                    "LRS-100-5": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 5V",
                            "Power": "90W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "30",
                        "image": "/img/Products/powersupplies/005.jpg",
                    },
                    "LRS-100-12": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 12V",
                            "Power": "102W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "35",
                        "image": "/img/Products/powersupplies/006.jpg",
                    },
                    "LRS-100-15": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 15V",
                            "Power": "105W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "37",
                        "image": "/img/Products/powersupplies/007.jpg",
                    },
                    "LRS-100-24": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "24V",
                            "Power": "108W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "42",
                        "image": "/img/Products/powersupplies/008.jpg",
                    },
                    "LRS-100-36": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 36V",
                            "Power": "100W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "45",
                        "image": "/img/Products/powersupplies/009.jpg",
                    },
                    "LRS-100-48": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 48V",
                            "Power": "110W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "50",
                        "image": "/img/Products/powersupplies/010.jpg",
                    },
                },
        },
    }
};

export const rangeOfProductsUa = {
    "categories": {
        "Панелі керування": {
            "Products":
                {
                    "Панель K923": {
                        "ItemCharacteristics":{
                            "ScreenResolution": "800x600",
                            "RAM": "1Gb",
                            "ModBusChannel": "1",
                            "PowerVoltage": "12V",
                        },
                        "Price": "190",
                        "image": "/img/Products/controlpanels/001.jpg",
                    },
                    "Панель K927": {
                        "ItemCharacteristics": {
                            "ScreenResolution": "1024x768",
                            "RAM": "1Gb",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "550",
                        "image": "/img/Products/controlpanels/002.jpg",
                    },
                    "Панель K1021": {
                        "ItemCharacteristics": {
                            "ScreenResolution": "1280x720",
                            "RAM": "1Gb",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "790",
                        "image": "/img/Products/controlpanels/003.jpg",
                    },
                },
        },
        "Програмовані контролери": {
            "Products":
                {
                    "Контролер MK120.01": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "16",
                            "NumberOfDigitalOutput": "32",
                            "ModBusChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "150",
                        "image": "/img/Products/controllers/001.jpg",
                    },
                    "Контролер MK120.03": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "16",
                            "NumberOfAnalogInput": "2",
                            "NumberOfAnalogOutput": "8",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "PowerVoltage": "24V",
                        },
                        "Price": "390",
                        "image": "/img/Products/controllers/002.jpg",
                    },
                    "Контролер MK120.05": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "8",
                            "NumberOfAnalogInput": "1",
                            "NumberOfAnalogOutput": "4",
                            "ModBusChannel": "2",
                            "PowerVoltage": "12V",
                        },
                        "Price": "420",
                        "image": "/img/Products/controllers/003.jpg",
                    },
                    "Контролер DVP20EX200T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "4",
                            "ModBusChannel": "1",
                            "RS-232": "1",
                            "TCPChannel": "1",
                            "CANopen": "master",
                            "Profibus":"slave",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "790",
                        "image": "/img/Products/controllers/004.jpg",
                    },
                    "Контролер DVP12SE11T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "4",
                            "NumberOfAnalogInput": "2",
                            "NumberOfAnalogOutput": "2",
                            "RS-232": "1",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "24V",
                        },
                        "Price": "590",
                        "image": "/img/Products/controllers/005.jpg",
                    },
                    "Контролер DVP28SV11T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "16",
                            "NumberOfDigitalOutput": "12",
                            "NumberOfAnalogInput": "4",
                            "NumberOfAnalogOutput": "2",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "590",
                        "image": "/img/Products/controllers/006.jpg",
                    },
                    "Контролер DVP14SS211T": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/007.jpg",
                    },
                    "Контролер DVP14SS212TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/008.jpg",
                    },
                    "Контролер DVP14SS213TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/009.jpg",
                    },
                    "Контролер DVP14SS214TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/010.jpg",
                    },
                    "Контролер DVP14SS215TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/011.jpg",
                    },
                    "Контролер DVP14SS216TX": {
                        "ItemCharacteristics": {
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "6",
                            "High-speed pulse output": "4 sets of 200kHz pulse output",
                            "High-speed counters": "1",
                            "ModBusChannel": "2",
                            "RS-232": "1",
                            "PowerVoltage": "100~240V",
                        },
                        "Price": "620",
                        "image": "/img/Products/controllers/012.jpg",
                    },
                },
        },
        "Компактні телеметричні модулі": {
            "Products":
                {
                    "Модуль MT-121": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "8",
                            "NumberOfAnalogInput": "3",
                            "NumberOfAnalogOutput": "1",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "750",
                        "image": "/img/Products/compactmodules/001.jpg",
                    },
                    "Модуль MT-151": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "Display": "OLED graphic display (128×64)",
                            "NumberOfDigitalInput": "16",
                            "NumberOfDigitalOutput": "12",
                            "NumberOfAnalogInputs": "6",
                            "NumberOfAnalogOutput": "1",
                            "RS-232": "1",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "USB": "Configurable USB-C port",
                            "Data and Event logger": "SD card",
                            "PowerVoltage": "12/24V",
                            "Battery Backup": "Buffered power supply (SLA battery support)",
                        },
                        "Price": "880",
                        "image": "/img/Products/compactmodules/002.jpg",
                    },
                    "Модуль MT-156": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "Display": "OLED graphic display (128×64)",
                            "NumberOfDigitalInput": "10",
                            "NumberOfDigitalOutput": "12",
                            "NumberOfAnalogInput": "2",
                            "RS-232": "1",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "USB": "Configurable USB-C port",
                            "Data and Event logger": "SD card",
                            "PowerVoltage": "12/24V",
                            "Battery Backup": "Buffered power supply (SLA battery support)",
                        },
                        "Price": "630",
                        "image": "/img/Products/compactmodules/003.jpg",
                    },
                },
        },
        "Спеціальні телеметричний модуль": {
            "Products":
                {
                    "Модуль MT-651": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "GPS receiver":"Built-in with internal antenna and accelerometer",
                            "Measurement channels": "6",
                            "Temperature sensor": "Internal",
                            "Remote communication": "GPRS and SMS",
                            "ModBusChannel": "1",
                            "Battery power supply": "external power source as optional",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "377",
                        "image": "/img/Products/specialtelemetrymodule/001.jpg",
                    },
                    "Модуль MT-652": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "GPS receiver":"Built-in with internal antenna and accelerometer",
                            "Measurement channel": "6",
                            "Temperature sensor": "Internal",
                            "Remote communication": "GPRS and SMS",
                            "ModBusChannel": "1",
                            "Data logger":"capacity 180 000 records",
                            "Battery power supply": "external power source as optional",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "530",
                        "image": "/img/Products/specialtelemetrymodule/002.jpg",
                    },
                    "Модуль MT-513": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "NumberOfDigitalInput": "8",
                            "NumberOfDigitalOutput": "2",
                            "AudioOutput": "1",
                            "Alarm transmission": "1",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "475",
                        "image": "/img/Products/specialtelemetrymodule/003.jpg",
                    },
                    "Модуль MT-221": {
                        "ItemCharacteristics": {
                            "GSM module": "2G/4G modem",
                            "ModBusChannel": "1",
                            "TCPChannel": "1",
                            "Real Time Clock":"RTC",
                            "Data logger":"0.1 sec",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "320",
                        "image": "/img/Products/specialtelemetrymodule/004.jpg",
                    },
                    "Модуль MTX-2050": {
                        "ItemCharacteristics": {
                            "GSM module": "4G LTE Cat. 1 modem with 2G/3G Fallback",
                            "NumberOfDigitalInput": "4",
                            "SerialPort": "2",
                            "TCPChannel": "1",
                            "Real Time Clock":"RTC",
                            "Data logger":"0.1 sec",
                            "Processor for data rules transmission":"Built-in",
                            "USB": "Configurable USB-C port",
                            "PowerVoltage": "12/24V",
                        },
                        "Price": "320",
                        "image": "/img/Products/specialtelemetrymodule/005.jpg",
                    },
                },
        },
        "Джерела живлення": {
            "Products":
                {
                    "Джерело DR-15-15": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "220V",
                            "OutputVoltage": "15V",
                            "Power": "15W",
                        },
                        "Price": "19",
                        "image": "/img/Products/powersupplies/001.jpg",
                    },
                    "Джерело DR-12-5": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "220V",
                            "OutputVoltage": "5V",
                            "Power": "12W",
                        },
                        "Price": "15",
                        "image": "/img/Products/powersupplies/002.jpg",
                    },
                    "Джерело DR-60-15": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "220V",
                            "OutputVoltage": "15V",
                            "Power": "60W",
                        },
                        "Price": "25",
                        "image": "/img/Products/powersupplies/003.jpg",
                    },
                    "Джерело DR-75-12": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "220V",
                            "OutputVoltage": "12V",
                            "Power": "75W",
                        },
                        "Price": "27",
                        "image": "/img/Products/powersupplies/004.jpg",
                    },
                    "Джерело LRS-100-5": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 5V",
                            "Power": "90W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "30",
                        "image": "/img/Products/powersupplies/005.jpg",
                    },
                    "Джерело LRS-100-12": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 12V",
                            "Power": "102W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "35",
                        "image": "/img/Products/powersupplies/006.jpg",
                    },
                    "Джерело LRS-100-15": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 15V",
                            "Power": "105W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "37",
                        "image": "/img/Products/powersupplies/007.jpg",
                    },
                    "Джерело LRS-100-24": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "24V",
                            "Power": "108W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "42",
                        "image": "/img/Products/powersupplies/008.jpg",
                    },
                    "Джерело LRS-100-36": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 36V",
                            "Power": "100W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "45",
                        "image": "/img/Products/powersupplies/009.jpg",
                    },
                    "Джерело LRS-100-48": {
                        "ItemCharacteristics": {
                            "Type": "AC-DC",
                            "InputVoltage": "AC 85~260V",
                            "OutputVoltage": "DC 48V",
                            "Power": "110W",
                            "Case" : "Metal, 1U low profile",
                        },
                        "Price": "50",
                        "image": "/img/Products/powersupplies/010.jpg",
                    },
                },
        },
    }
};